@echo off
echo Stopping MySQL Docker container...
docker-compose down

echo Removing volumes (this will delete all data)...
echo Press any key to continue or Ctrl+C to cancel...
pause > nul
docker-compose down -v
